#!/usr/bin/env sh

set -euxo pipefail

# Steps:

# - Stash (any) changes so we can switch branches later

git stash


# - Build

nix build .


# - Switch branches

git checkout gh-pages


# - Copy the built website to the root, but don't delete things we want. (i.e.
# the things that are peristed due to branch switches; those things in the
# gitignore file.)

rsync -a --filter='P .git'             \
         --filter='P .gitignore'       \
         --filter='P node_modules'     \
         --filter='P result'           \
         --filter='P .vitepress/cache' \
         --filter='P .vitepress/dist'  \
         --delete-excluded \
         --no-p \
         result/ .


# - Add, commit and push

git add -A
git commit -m "Update." || true
git push origin gh-pages


# - Bring everything back

git checkout main
git stash pop
